---
- name: Backup fortios configurations
  hosts: appc_fortigate_vfwl
  gather_facts: false

  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars
      delegate_to: localhost

  tasks:
    - name: Collect device running configs and write to a temporary file
      ansible.builtin.import_role:
        name: role-fortinet-config-backup
      vars:
        _backup_: true
        _tmp_root_dir_: "{{ tmp_base_dir }}"
        _local_file_path_: "{{ tmp_base_dir }}/{{ git_repo_config_backup_dir_path }}/{{ config_backup_file_name }}"
        